name: 'Setup Python Environment'
description: 'Setup Python, install uv, and install dependencies'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/0.5.9/install.sh | sh
      shell: bash
    - name: Install dependencies
      run: uv sync --frozen
      shell: bash
