name: 'Setup Python Environment'
description: 'Setup Python, install uv, and install dependencies'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      run: pip install uv==0.8.13
      shell: bash
    - name: Install dependencies
      run: uv sync --locked
      shell: bash
    - name: Audit dependencies
      run: uv run pip-audit
      shell: bash
