name: Check Commits on main

on:
  push:
    branches:
      - main

jobs:
  check-main-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-env
      - run: uv run aserehe check
